### ISSUE TITLE
Certificate changes ...

### ISSUE THREAD

**Issue by chris2286266** [Federal-Ministry-of-Health-AT/green-pass-overview#11]
To inform all of you: The ssl (tls) server certificates for *qr.gv.at will be renewed soon.

This affects the servers https://dgc-trusttest.qr.gv.at and https://dgc-trust.qr.gv.at

dgc-trusttest.qr.gv.at - Wednesday, 30.3.2022 12:00 CET
dgc-trust.qr.gv.at - Wednesday, 13.4.2022 12:00 CET

If you have no special implementation (e.g. certificate pinning) in place, the renewal of the certificates shall have no impact on your systems.

**Comment by HQJaTu** [comment]
It seems maintainers aren't' bothering anymore. Trust list production certificate expired `Not After : Jun 19 12:09:49 2023 GMT` and there isn''t any other known source for it.

**Comment by chris2286266** [comment]
The DCC Infrastructure has been discontinued per end of June 2023.
We will update the page asap.
