### ISSUE TITLE
https://dgc-trusttest.qr.gv.at/rulessig has expired

### ISSUE THREAD

**Issue by lazka** [Federal-Ministry-of-Health-AT/green-pass-overview#13]
The signature currently states it is valid from `2022-03-21T07:05:53+00:00` until `2022-03-23T07:05:53+00:00` which has passed.

This is just the test data, but I use it in CI :)

**Comment by chris-baumann-at** [comment]
My system tells me the following right now:
From: Thu, 15 Apr 2021 00:00:00 GMT
To: Wed, 20 Apr 2022 23:59:59 GMT

**Comment by lazka** [comment]
The signatures of the trust data is always only valid for 2 days, so I think we are talking about different things :)

I'm still seeing the same error.

**Comment by chris-baumann-at** [comment]
Yes, you are right, sorry for the mixup.
The trustlist (and other data like business rules and value sets) should be generated periodically (e.h. every hour) and have a validity of 48 hours. The service at the Q-system was updated an will be live again soon.

**Comment by lazka** [comment]
Thanks! 🙏

**Comment by lazka** [comment]
just fyi, it has expired again 4 days ago -> `To: 2022-05-07T07:05:47+00:00`

edit: works again now
