### ISSUE TITLE
Question re certificate validity/expiration

### ISSUE THREAD

**Issue by lazka** [Federal-Ministry-of-Health-AT/green-pass-overview#14]
I'm being overly cautious here, so feel free to ignore :)

The production certificate expires "Jul  2 13:46:21 2022 GMT" and the test one "Jun 19 13:04:47 2022 GMT" which is in 2-3 months.

Are there any plans to update those?

thanks

**Comment by chris-baumann-at** [comment]
Hi, the certificates are updated now.

**Comment by lazka** [comment]
Thanks! 🙏

Sadly [hcert-kotlin](https://github.com/ehn-dcc-development/hcert-kotlin) can't handle the new cert in combination with the existing trust data. I've filed an issue there -> https://github.com/ehn-dcc-development/hcert-kotlin/issues/75
