### ISSUE TITLE
Getting a Certificate

### ISSUE THREAD

**Issue by dominikstrasser** [Federal-Ministry-of-Health-AT/green-pass-overview#2]
Hey.

How can i get access (official certificate - not the one in this repo) to download the trustlist/business rules/value sets. 

Thanks
Dominik Strasser
dominik.strasser@netural.com
[covidoor.com](covidoor.com)

**Comment by asitplus-pteufl** [comment]
Can you elaborate?
The links in the README also point to the prod. Lists for trust/rules/valuesets. the prod. certificate for validating the lists is also published in the README.
However, there is no access limitation yet, this will be introduced, you will need to apply for an API key (infos will be posted here).

**Comment by dominikstrasser** [comment]
Ok great. I was just not sure if I'm allowed to use the certificate from this repo since the readme says something about the "one-time registration".
[https://github.com/Federal-Ministry-of-Health-AT/green-pass-overview#getting-access-to-trust-list-business-rules-and-value-sets](https://github.com/Federal-Ministry-of-Health-AT/green-pass-overview#getting-access-to-trust-list-business-rules-and-value-sets)

But if we don't have to do this now i'm satisfied :-) 
thanks
Dominik

**Comment by asitplus-pteufl** [comment]
the reg. will be necessary, but for now the lists are public.

**Comment by asitplus-pteufl** [comment]
as add. remark: there will be further information on the rules format (especially the AT-rules for the national use cases), since there is a mapping between the validation profiles (e.g. entry-tests) and the AT-rules. Also, the national AT-Rules are not yet available in the prod. list. this will change after detailed test procedures.

**Comment by dominikstrasser** [comment]
Ok understand. As far as i see the official "business rules" are not yet in use in greenchecker and qr.gv.at - so that's probably why...

For now i guess i will then manually download the rulesets and adapt them accordingly until there is more informations on the "profiles".
Is there an ETA on the profiles?

**Comment by asitplus-pteufl** [comment]
soon....

**Comment by lazka** [comment]
Just wondering, what's the reason for making this registration only? It's more or less static and public data.
