### ISSUE TITLE
Standardized name not shown

### ISSUE THREAD

**Issue by ofek-b** [Federal-Ministry-of-Health-AT/green-pass-overview#5]
Some countries that use different alphabets issue EU-conform QR-codes, and store both native ("name" field) and Latin ("standardized name" field) script on the QR-code. The app only uses the "name" field, making it practically unusable for people vaccinated in those countries, at least in checks where they only read the text (and don't scan the code). It would be really helpful if the standardized name will be used at the title, at least in cases where the name is in a different alphabet.

~~See screenshot below from the identical for this case Swiss app.~~

If you scan the code with the Robert-Koch app, it shows the standardized name as one of the fields (though still only the normal name at the title...):

Thanks!

**Comment by chris-baumann-at** [comment]
This is an issue of the corresponding App/s and has nothing to do with this repository.
