### ISSUE TITLE
AT-METADATA engine and NG-W-MD/NG-MD/ET-W-MD/ET-MD

### ISSUE THREAD

**Issue by lazka** [Federal-Ministry-of-Health-AT/green-pass-overview#7]
I see that there are rules referencing a new engine: https://raw.githubusercontent.com/digital-blueprint/dgc-trust-mirror/main/prod.json/rules-at.md

Is there any information available on what's the difference to certlogic and if they should be used?

Thanks!

**Comment by pagdot** [comment]
Just documenting my own findings. Maybe another one knows more:

Overall structure:

```
(<type>(-<state>)(-MD))
```

**Types**:

Type | Deutsch | English
:--- | :-------- | :-------
BG | Berufsgruppen | requirement for working?
ET | Eintritt | entry to ...
NG | Nachtgastronomie | night gastronomy

**States**:

Name | Deutsch | English
:----- | :-------- | :-------
BGLD | Burgenland | Burgenland 
KTN | Kärnten | Carinthia
NOE | Niederösterreich | Lower Austria
OOE | Oberösterreich | Upper Austria
SBG | Salzburg | Salzburg
STMK | Steiermark | Styria
T | Tirol | Tyrol
VBG | Vorarlberg | Vorarlberg
W | Wien | Vienna

I don't know the meaning of the `MD`, which may appear at the end of some.

Current list:

```
BG
ET
ET-BGLD
ET-BGLD-MD
ET-KTN
ET-KTN-MD
ET-MD
ET-NOE
ET-NOE-MD
ET-OOE
ET-OOE-MD
ET-SBG
ET-SBG-MD
ET-STMK
ET-STMK-MD
ET-T
ET-T-MD
ET-VBG
ET-VBG-MD
ET-W
ET-W-MD
NG
NG-BGLD
NG-BGLD-MD
NG-KTN
NG-KTN-MD
NG-MD
NG-NOE
NG-NOE-MD
NG-OOE
NG-OOE-MD
NG-SBG
NG-SBG-MD
NG-STMK
NG-STMK-MD
NG-T
NG-T-MD
NG-VBG
NG-VBG-MD
NG-W
NG-W-MD
```

**Comment by chris2286266** [comment]
The "MD" (METADATA) part of the Region field indicates, that the rule is not a CERTLOGIC rule (which returns true or false) but a rule returning a date indicating until when the certificate is valid.
This date can e.g. be displayed in wallet apps. If such a feature is not needed, the “MD” rules can be ignored.

**Comment by lazka** [comment]
@chris2286266 ah, thanks, makes sense

I'm currently using a "binary search" + the original rules to figure out the end date :P

For anyone curious, here is a diff of one rule:

<details>

```diff
--- 2.json	2021-11-16 15:08:47.021823544 +0100
+++ 1.json	2021-11-16 15:08:43.749810780 +0100
@@ -1,10 +1,10 @@
 {
-    "Identifier": "RR-AT-0002",
+    "Identifier": "RR-AT-0002-MD",
     "Type": "Acceptance",
     "Country": "AT",
     "Version": "1.0.0",
     "SchemaVersion": "1.0.0",
-    "Engine": "CERTLOGIC",
+    "Engine": "AT-METADATA",
     "EngineVersion": "0.7.5",
     "CertificateType": "Recovery",
     "Description": [
@@ -29,29 +29,16 @@
                 "var": "payload.r.0"
             },
             {
-                "not-after": [
+                "plusTime": [
                     {
-                        "plusTime": [
-                            {
-                                "var": "external.validationClock"
-                            },
-                            0,
-                            "day"
-                        ]
+                        "var": "payload.r.0.fr"
                     },
-                    {
-                        "plusTime": [
-                            {
-                                "var": "payload.r.0.fr"
-                            },
-                            180,
-                            "day"
-                        ]
-                    }
+                    180,
+                    "day"
                 ]
             },
-            true
+            null
         ]
     },
-    "Region": "ET-SBG"
+    "Region": "ET-SBG-MD"
 }
```

</details>

**Comment by pagdot** [comment]
Documented now in 788696ea51ccae6526c3eefb79eebd2385ad8716

@lazka I think we can close this issue

**Comment by lazka** [comment]
Thanks, perfect.

Also thanks for clarifying the "fair-use policy" :+1:
