### ISSUE TITLE
Error: TRUST_LIST_EXPIRED

### ISSUE THREAD

**Issue by dominikstrasser** [Federal-Ministry-of-Health-AT/green-pass-overview#8]
Hey.

I'm facing issues since today to init the verifier. but there was no code change on my side.

Did something change on the trustlist side of wich i should be aware of? Do i need a new certificate (I'm using the one here on github)

The error occurs when run the the `VerifierTrustList`: 

```
this.verifier = new this.hcert.VerifierTrustList(pemCert, resultContent, resultSignature);
```

![image](https://user-images.githubusercontent.com/7978324/141749847-ebf86b4a-9700-47c8-b316-5f92b5563ad2.png)

all the best
Dominik

**Comment by pagdot** [comment]
https://greencheck.gv.at/ and the GreenCheck App are not working too. Probably because of this issue

**Comment by lazka** [comment]
same here. android and iOS apps are broken as well

**Comment by pagdot** [comment]
Works now (at least Android and web)

**Comment by lazka** [comment]
Can confirm, the API returns valid data again

Looking at my mirror I see that in the last two days the prod signature wasn't updated, only the test one: https://github.com/digital-blueprint/dgc-trust-mirror/commits/main

So maybe some cron job didn't run...

**Comment by dominikstrasser** [comment]
Great! Thanks for the update. 
closed
